In [1]:
import pandas as pd
import matplotlib.pyplot as plt

raw_data = pd.read_csv("../data/analysis_table/data_cleaned.csv")
session_df = pd.read_csv("../data/analysis_table/sess ion_table.csv")
user_df = pd.read_csv("../data/analysis_table/user_table.csv")
funnel = pd.read_csv("../data/analysis_table/funnel_table.csv")

In [ ]:
raw_data['product_category'] = raw_data['category_code'].str.split(".").str[0]

In [19]:
category_session = (raw_data.groupby(['user_id', 'user_session', 'product_category'])
                      .agg(has_view = ('event_type', lambda x: (x == 'view').any()),
                           has_cart = ('event_type', lambda x: (x == 'cart').any()),
                           has_purchase = ('event_type', lambda x: (x == 'purchase').any()))
                           .reset_index()
                           )

category_session.head()

# for each product category, what actions was done by user, in each session

,user_id,user_session,product_category,has_view,has_cart,has_purchase
0,106416780,9bfd655e-e5f0-4cc5-897f-c0aa1748ae0e,appliances,True,False,False
1,107020671,04f1a36a-3202-4d4e-b9cb-e8d3a0dcf3a4,auto,True,False,False
2,107020671,effeaf46-19f9-4f9a-a31b-f6789edac8b7,auto,True,False,False
3,109306116,8b68f035-82be-447a-8091-2cd7282ffcc3,furniture,True,False,False
4,111805635,259092ef-7080-498c-b3c2-8a8291f7ca69,auto,True,False,False

In [21]:
category_conversion = (category_session.groupby('product_category')
                       .agg(products_viewed = ('has_view', 'sum'),
                            products_carted = ('has_cart', 'sum'),
                            products_purchased = ('has_purchase', 'sum'))
                            .reset_index()
                            )

category_conversion

   product_category  products_viewed  products_carted  products_purchased
0       accessories            20478              995                 417
1           apparel           139831             6803                2509
2        appliances           334978            41652               17656
3              auto            66623             4989                2022
4         computers           188442            15022                5940
5      construction            50470             4315                1584
6      country_yard             1124               38                   8
7       electronics          1197480           176252               82344
8         furniture           103949             5377                2033
9              kids            52925             2686                1053
10         medicine             1280              177                  68
11            sport            14055              714                 245
12       stationery              975               77                  31

In [22]:
category_conversion['view_to_cart_rate'] = (category_conversion['products_carted']/category_conversion['products_viewed'])
category_conversion['cart_to_purchase_rate'] = (category_conversion['products_purchased']/category_conversion['products_carted'])
category_conversion['view_to_purchase_rate'] = (category_conversion['products_purchased']/category_conversion['products_viewed'])

category_conversion = category_conversion.round(2)

category_conversion

,product_category,products_viewed,products_carted,products_purchased,view_to_cart_rate,cart_to_purchase_rate,view_to_purchase_rate
0,accessories,20478,995,417,0.05,0.42,0.02
1,apparel,139831,6803,2509,0.05,0.37,0.02
2,appliances,334978,41652,17656,0.12,0.42,0.05
3,auto,66623,4989,2022,0.07,0.41,0.03
4,computers,188442,15022,5940,0.08,0.40,0.03
5,construction,50470,4315,1584,0.09,0.37,0.03
6,country_yard,1124,38,8,0.03,0.21,0.01
7,electronics,1197480,176252,82344,0.15,0.47,0.07
8,furniture,103949,5377,2033,0.05,0.38,0.02
9,kids,52925,2686,1053,0.05,0.39,0.02
10,medicine,1280,177,68,0.14,0.38,0.05
11,sport,14055,714,245,0.05,0.34,0.02
12,stationery,975,77,31,0.08,0.40,0.03

In [23]:
# AOV (Average Order Value) by category

purchase_df = raw_data[raw_data['event_type'] == 'purchase']

# group by user_session to know the total purchase value in the same order
order_value = (purchase_df.groupby(['user_session', 'product_category'])['price'].sum().reset_index(name = 'order_value'))

aov_by_category = (order_value.groupby('product_category')['order_value'].mean().sort_values(ascending = False).reset_index(name = 'AOV')).round(2)

aov_by_category

   product_category     AOV
0       electronics  492.59
1         computers  443.06
2             sport  262.15
3         furniture  256.47
4        appliances  209.29
5      country_yard  153.36
6              auto  133.93
7      construction  132.14
8              kids  127.38
9           apparel   95.13
10         medicine   52.66
11      accessories   51.99
12       stationery   16.91

In [25]:
product_summary_by_category = pd.merge(aov_by_category, category_conversion, on = 'product_category', how = 'left')

product_summary_by_category = product_summary_by_category.sort_values('view_to_purchase_rate', ascending = False)

product_summary_by_category

,product_category,AOV,products_viewed,products_carted,products_purchased,view_to_cart_rate,cart_to_purchase_rate,view_to_purchase_rate
0,electronics,492.59,1197480,176252,82344,0.15,0.47,0.07
4,appliances,209.29,334978,41652,17656,0.12,0.42,0.05
10,medicine,52.66,1280,177,68,0.14,0.38,0.05
1,computers,443.06,188442,15022,5940,0.08,0.40,0.03
6,auto,133.93,66623,4989,2022,0.07,0.41,0.03
7,construction,132.14,50470,4315,1584,0.09,0.37,0.03
12,stationery,16.91,975,77,31,0.08,0.40,0.03
2,sport,262.15,14055,714,245,0.05,0.34,0.02
3,furniture,256.47,103949,5377,2033,0.05,0.38,0.02
8,kids,127.38,52925,2686,1053,0.05,0.39,0.02
9,apparel,95.13,139831,6803,2509,0.05,0.37,0.02
11,accessories,51.99,20478,995,417,0.05,0.42,0.02
5,country_yard,153.36,1124,38,8,0.03,0.21,0.01